"""osce figure rejection tracking

Revision ID: 0987665ceff5
Revises: 8bacbebcfc33
Create Date: 2026-07-26 14:45:07.139840
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0987665ceff5'
down_revision: str | None = '8bacbebcfc33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_figures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_urls', sa.JSON(), nullable=True))
        # server_default is required: osce_figures already holds rows, and a
        # NOT NULL column cannot be added to them without one.
        batch_op.add_column(
            sa.Column('rejection_count', sa.Integer(), nullable=False,
                      server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_figures', schema=None) as batch_op:
        batch_op.drop_column('rejection_count')
        batch_op.drop_column('rejected_urls')

    # ### end Alembic commands ###
