"""add osce circuits sessions responses grades

Revision ID: 1a4ef0179047
Revises: 67cb07c44d8d
Create Date: 2026-07-26 00:37:17.382385
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa
revision: str = '1a4ef0179047'
down_revision: str | None = '67cb07c44d8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_discarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_clips_sha256'), ['sha256'], unique=False)

    op.create_table('osce_circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('station_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osce_circuits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_circuits_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_osce_circuits_user_id'), ['user_id'], unique=False)

    op.create_table('osce_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_timed', sa.Boolean(), nullable=False),
    sa.Column('current_prompt_index', sa.Integer(), nullable=False),
    sa.Column('grading_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['osce_circuits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['osce_stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osce_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_sessions_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osce_sessions_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osce_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('osce_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('prompt_label', sa.String(length=10), nullable=False),
    sa.Column('examiner_pass', sa.Integer(), nullable=False),
    sa.Column('awarded_marks', sa.Float(), nullable=False),
    sa.Column('available_marks', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['osce_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'prompt_label', 'examiner_pass', name='uq_osce_grade_pass')
    )
    with op.batch_alter_table('osce_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_grades_session_id'), ['session_id'], unique=False)

    op.create_table('osce_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('prompt_label', sa.String(length=10), nullable=False),
    sa.Column('prompt_index', sa.Integer(), nullable=False),
    sa.Column('audio_clip_id', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_edited', sa.Text(), nullable=True),
    sa.Column('transcription_status', sa.String(length=20), nullable=False),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_clip_id'], ['audio_clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['osce_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'prompt_label', name='uq_osce_response_prompt')
    )
    with op.batch_alter_table('osce_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_responses_session_id'), ['session_id'], unique=False)

    op.create_table('osce_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('total_awarded', sa.Float(), nullable=False),
    sa.Column('total_available', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('cut_score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('flagged_prompts', sa.JSON(), nullable=True),
    sa.Column('ungraded_prompts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['osce_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('osce_results')
    with op.batch_alter_table('osce_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_responses_session_id'))

    op.drop_table('osce_responses')
    with op.batch_alter_table('osce_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_grades_session_id'))

    op.drop_table('osce_grades')
    with op.batch_alter_table('osce_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_osce_sessions_station_id'))
        batch_op.drop_index(batch_op.f('ix_osce_sessions_circuit_id'))

    op.drop_table('osce_sessions')
    with op.batch_alter_table('osce_circuits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_circuits_user_id'))
        batch_op.drop_index(batch_op.f('ix_osce_circuits_scheduled_for'))

    op.drop_table('osce_circuits')
    with op.batch_alter_table('audio_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_clips_sha256'))

    op.drop_table('audio_clips')
    # ### end Alembic commands ###
