"""station patient demographic

Revision ID: 510501aa7893
Revises: 0987665ceff5
Create Date: 2026-07-26 16:06:14.775165
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '510501aa7893'
down_revision: str | None = '0987665ceff5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_demographic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.drop_column('patient_demographic')

    # ### end Alembic commands ###
