"""add osce station prompts

Revision ID: 67cb07c44d8d
Revises: 3c6e7d47eb68
Create Date: 2026-07-25 21:06:12.965437
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '67cb07c44d8d'
down_revision: str | None = '3c6e7d47eb68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompts', sa.JSON(), nullable=True))
        # server_default is required: the table already holds 36 stations, and
        # neither SQLite nor PostgreSQL can add a NOT NULL column to populated
        # rows without one.
        batch_op.add_column(
            sa.Column(
                'prompts_status',
                sa.String(length=20),
                nullable=False,
                server_default='none',
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.drop_column('prompts_status')
        batch_op.drop_column('prompts')

    # ### end Alembic commands ###
