"""osce findings split and station figures

Revision ID: 8bacbebcfc33
Revises: 1a4ef0179047
Create Date: 2026-07-26 00:57:07.729839
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa
revision: str = '8bacbebcfc33'
down_revision: str | None = '1a4ef0179047'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osce_figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('wanted_description', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['osce_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osce_figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_figures_station_id'), ['station_id'], unique=False)

    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('findings_given', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('findings_elicited', sa.Text(), nullable=True))
        # server_default is required: the table already holds 36 stations, so a
        # NOT NULL column cannot be added without one.
        batch_op.add_column(
            sa.Column(
                'findings_split_status',
                sa.String(length=20),
                nullable=False,
                server_default='none',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.drop_column('findings_split_status')
        batch_op.drop_column('findings_elicited')
        batch_op.drop_column('findings_given')

    with op.batch_alter_table('osce_figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_figures_station_id'))

    op.drop_table('osce_figures')
    # ### end Alembic commands ###
