"""initial schema

Revision ID: c3bdb0781602
Revises: 
Create Date: 2026-07-25 16:18:51.068881
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c3bdb0781602'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subspecialty', sa.String(length=60), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subspecialty', 'code', name='uq_curriculum_sub_code')
    )
    with op.batch_alter_table('curriculum_standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_standards_subspecialty'), ['subspecialty'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_log_source'), ['source'], unique=False)

    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('paper_type', sa.String(length=20), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('paper_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('cut_score', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('exam_period', sa.String(length=60), nullable=True),
    sa.Column('document_kind', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_sha256'), ['sha256'], unique=False)

    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_task'), ['task'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('is_timed', sa.Boolean(), nullable=False),
    sa.Column('reading_notes', sa.Text(), nullable=True),
    sa.Column('grading_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_page_url', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('licence', sa.String(length=120), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_sha256'), ['sha256'], unique=True)

    op.create_table('osce_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_number', sa.Integer(), nullable=True),
    sa.Column('subspecialty', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('case_summary', sa.Text(), nullable=True),
    sa.Column('aims', sa.JSON(), nullable=True),
    sa.Column('patient_history', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('cohort_performance', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('exam_period', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('angoff_expected', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osce_stations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_osce_stations_subspecialty'), ['subspecialty'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=10), nullable=False),
    sa.Column('subspecialty', sa.String(length=60), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('curriculum_standard_raw', sa.Text(), nullable=True),
    sa.Column('curriculum_codes', sa.JSON(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('exam_period', sa.String(length=60), nullable=True),
    sa.Column('original_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('angoff_expected', sa.Float(), nullable=True),
    sa.Column('angoff_rationale', sa.Text(), nullable=True),
    sa.Column('model_answer_status', sa.String(length=20), nullable=False),
    sa.Column('generation_meta', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subspecialty'), ['subspecialty'], unique=False)

    op.create_table('exam_paper_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_paper_question')
    )
    with op.batch_alter_table('exam_paper_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_paper_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_paper_questions_question_id'), ['question_id'], unique=False)

    op.create_table('examiner_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('examiner_number', sa.Integer(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.Column('cohort_impression', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examiner_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_examiner_feedback_question_id'), ['question_id'], unique=False)

    op.create_table('question_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('preamble', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_parts_question_id'), ['question_id'], unique=False)

    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('total_awarded', sa.Float(), nullable=False),
    sa.Column('total_available', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('cut_score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('subspecialty_breakdown', sa.JSON(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('flagged_parts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['question_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'part_id', name='uq_answer_session_part')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)

    op.create_table('figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('wanted_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['question_parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figures_question_id'), ['question_id'], unique=False)

    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('examiner_pass', sa.Integer(), nullable=False),
    sa.Column('awarded_marks', sa.Float(), nullable=False),
    sa.Column('available_marks', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['question_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'part_id', 'examiner_pass', name='uq_grade_unique_pass')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_session_id'), ['session_id'], unique=False)

    op.create_table('model_answer_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('from_examiner_feedback', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('accepted_alternatives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['question_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_answer_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_answer_points_part_id'), ['part_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_answer_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_answer_points_part_id'))

    op.drop_table('model_answer_points')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_session_id'))
        batch_op.drop_index(batch_op.f('ix_grades_part_id'))

    op.drop_table('grades')
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figures_question_id'))

    op.drop_table('figures')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_answers_part_id'))

    op.drop_table('answers')
    op.drop_table('session_results')
    with op.batch_alter_table('question_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_parts_question_id'))

    op.drop_table('question_parts')
    with op.batch_alter_table('examiner_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examiner_feedback_question_id'))

    op.drop_table('examiner_feedback')
    with op.batch_alter_table('exam_paper_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_paper_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_exam_paper_questions_paper_id'))

    op.drop_table('exam_paper_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subspecialty'))
        batch_op.drop_index(batch_op.f('ix_questions_status'))
        batch_op.drop_index(batch_op.f('ix_questions_source'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))

    op.drop_table('questions')
    with op.batch_alter_table('osce_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osce_stations_subspecialty'))
        batch_op.drop_index(batch_op.f('ix_osce_stations_status'))

    op.drop_table('osce_stations')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_sha256'))

    op.drop_table('images')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_paper_id'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_task'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_created_at'))

    op.drop_table('ai_calls')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_sha256'))

    op.drop_table('source_documents')
    op.drop_table('settings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    op.drop_table('exam_papers')
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_log_source'))
        batch_op.drop_index(batch_op.f('ix_error_log_level'))
        batch_op.drop_index(batch_op.f('ix_error_log_created_at'))

    op.drop_table('error_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('curriculum_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_standards_subspecialty'))

    op.drop_table('curriculum_standards')
    # ### end Alembic commands ###
